### ISSUE TITLE
Rails 7.2 support

### ISSUE THREAD

**Issue by elliotcm** [braintree/pg_ha_migrations#104]
Hello,

Rails 7.2 was recently released, would it be possible for this gem to be updated to add it to the allowed versions list?

Hopefully not too much hassle, looking at the 7.2 release notes.

Many thanks!

**Comment by AlexMooney** [comment]
This is currently blocked by https://github.com/jcoleman/relation_to_struct not supporting Rails 7.2.  I've opened a PR over there: https://github.com/jcoleman/relation_to_struct/pull/21 and when it's merged, I'll open a PR here for 7.2 support if someone else doesn't beat me to it.

**Comment by rkrage** [comment]
This has been merged, but we have some backwards incompatible changes on master (changing some defaults for config values). After we implement https://github.com/braintree/pg_ha_migrations/issues/63 (hopefully very soon), we'll publish version `2.0.0`
