### ISSUE TITLE
Make monkey-patching of ActiveRecord::Migration methods optional

### ISSUE THREAD

**Issue by tragiclifestories** [braintree/pg_ha_migrations#17]
Really glad this exists - thanks people!

One thing that would make things easier is if it was possible not to replace the original implementation of the various ActiveRecord::Migration DDL methods with versions that raise errors. The use case for this is incrementally rolling this out in an organisation with a big old monolith with multiple teams etc. rolling it out. We'd like to have the choice ideally.

Happy to do a PR if one would be accepted.

**Comment by redneckbeard** [comment]
Hey James -- we'd be okay with that if it were a configurable option and
not the default.
