### ISSUE TITLE
Setup travis builds

### ISSUE THREAD

**Issue by JonMR** [braintree/pg_ha_migrations#2]
We should have travis builds running. Ideally, we'd test against multiple versions of rails.

**Comment by jcoleman** [comment]
Added with b23607730ad6e864dd344e24bf3f45f0331dace6 and 45c6d500f3f5d879cc04cf529f0efba7ca09ef63 though we don't yet have appraisal for testing against multiple versions of Rails.

@JonMR Do you want to close this and maybe track appraisal as a separate requirement?

**Comment by JonMR** [comment]
Good idea. I'll close this and open a new issue for adding appraisal.
