### ISSUE TITLE
Definition of `unsafe_add_column` is unused

### ISSUE THREAD

**Issue by tragiclifestories** [braintree/pg_ha_migrations#22]
While trying to test some lock scenarios, I spotted this little problem.

Basically, unlike all the other `unsafe_` methods, this one - along with `unsafe_make_column_not_nullable` - is supposed to have a custom implementation that uses the lock acquisition logic rather than delegating directly to `ActiveRecord::Migration`. However, the custom implementation are further away in the inheritance chain, so it never gets called - the delegate in `unsafe_statements` gets called instead.

I thought initially that this was a bug I'd introduced, but I've reproduced it on 1.0.0 as well. 

Fix should be as simple as removing the delegate from `unsafe_statements` ...  

EDIT: only `unsafe_add_column` is affected, not `unsafe_make_column_not_nullable` as I initially thought.

**Comment by tragiclifestories** [comment]
> Fix should be as simple as removing the delegate from unsafe_statements ...

Actually, it isn't 😞

**Comment by jcoleman** [comment]
Is there a reason why the lock acquisition shouldn't happen [here](https://github.com/braintree/pg_ha_migrations/blob/7b0a83b38c82cf249b4272e0f17290d415b38eae/lib/pg_ha_migrations/safe_statements.rb#L32) instead of inside the `unsafe_add_column` method?

I'm probably missing something obvious...

**Comment by tragiclifestories** [comment]
From what I understand, the idea is that even if it is impossible to say that the column-add operation itself is safe from an availability point of view, it is still safer to use the lock acquisition loop than not to do so, so `unsafe_add_column` is still 'safer' for it than vanilla AR. 

Cf. the [readme](xhttps://github.com/braintree/pg_ha_migrations/blob/master/README.md#unsafe_add_column):

> Unsafely add a column, but do so with a lock that is safely acquired.

**Comment by stephenreid** [comment]
See also https://github.com/braintree/pg_ha_migrations/pull/34

add_column on PostgreSQL > 11 generally shouldn't require this lock; and maybe not even unsafe nomenclature.

**Comment by JonMR** [comment]
I closed #23 since it's been open for so long, but we think that would make a great starting point.

**Comment by jcoleman** [comment]
The original bug report here was fixed in #47. I'd been leaving this open because of additional discussion that'd happened here, but I've decided to close this in favor of opening a new issue (#63) to discuss that broader question.
