### ISSUE TITLE
Upgrade to Rails 6

### ISSUE THREAD

**Issue by ekampp** [braintree/pg_ha_migrations#32]
Hey there. 

I would love to use this gem for one of our projects. 

I just wanted to know: What's the timeline and roadmap for moving to Rails 6?

If there isn't one, is there anything I can do to help? And is there anything I should be particularly observant about when I start to do work? 

Best,

**Comment by roman-melnyk** [comment]
hi! any updates on this issue?

**Comment by jcoleman** [comment]
@roman-melnyk @ekampp Sorry, I saw this in email and meant to respond, but lost track of it in a flood of alerting email.

I'd imagine we'd need to working upgrading to Rails 6 sometime in 2020, but there isn't a scheduled timeline for that yet.

If you'd like to start working on it, we'd love to have that contribution! I'd probably begin by modifying the [Rails dependency](https://github.com/braintree/pg_ha_migrations/blob/master/pg_ha_migrations.gemspec#L40), and then running the full test suite. You'll probably also want to include the new 6.0 migration class in the [allowed versions list](https://github.com/braintree/pg_ha_migrations/blob/master/lib/pg_ha_migrations/allowed_versions.rb). If all existing tests pass for existing versions, that'd be helpful know, and it'd be helpful to know if ones fail specifically for the 6.0 migration subclass.

Given that ActiveRecord 6 has been working a fair amount on how connection management works, I could imagine a lot of tests failing or almost none at all, which I realize isn't particularly helpful :)

**Comment by roman-melnyk** [comment]
@jcoleman created a PR, few specs failed locally, but it might be because of different PG version, please check them locally

**Comment by roman-melnyk** [comment]
@jcoleman could you please test locally this [PR](https://github.com/braintree/pg_ha_migrations/pull/33) to see if we need further work on updating?

**Comment by jcoleman** [comment]
This was fixed by #33.
