### ISSUE TITLE
Unsafe make_column_not_nullable

### ISSUE THREAD

**Issue by 14113** [braintree/pg_ha_migrations#82]
In the method `unsafe_make_column_not_nullable`, it's called `safely_acquire_lock_for_table`. 

Is the prefix **unsafe_** correct?

https://github.com/braintree/pg_ha_migrations/blob/92ec97c9ffca4785b48ca84bb71afb914e827776/lib/pg_ha_migrations/safe_statements.rb#L143-L147

**Comment by rkrage** [comment]
Yes. You might see a mix of safe and unsafe calls in the _implementation_ of various methods, but that doesn't change the overall safety of the operation
